INSERT INTO "AUTH_USER" (ID, PASSWORD, IS_SUPERUSER, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, IS_STAFF, IS_ACTIVE, DATE_JOINED)
VALUES (1, 'pbkdf2_sha256$36000$WYuzSIjT0w92$ijFf3blCRZ2jeVlRyLvbfzceZjth/pAoIKm8P7qfuac=', 1, 'superuser', 'super_first', 'super_last', 'vlad@gmail.com', 0, 1, '26-DEC-17 03.04.07.834070000 AM');
COMMIT;
INSERT INTO "AUTH_USER" (ID, PASSWORD, IS_SUPERUSER, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, IS_STAFF, IS_ACTIVE, DATE_JOINED)
VALUES (2, 'pbkdf2_sha256$36000$HoV5DnJbyTj0$rcyF0liKWMYdj8qPkViudklfLGL3vZATQUNG+k2dapg=', 0, 'testuser', 'Admin', 'Admin', 'admin@gmail.com', 0, 1, '26-DEC-17 04.19.00.000000000 PM');
COMMIT;
INSERT INTO "AUTH_USER" (ID, PASSWORD, IS_SUPERUSER, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, IS_STAFF, IS_ACTIVE, DATE_JOINED)
VALUES (2, 'pbkdf2_sha256$36000$OzLNzDku3X1c$GYsVqRZJquGSCEG3jziqpzNnkiL2p+Gt1ljDi5agXsc=', 0, 'otheruser', 'Other', 'User', 'other@gmail.com', 0, 1, '26-DEC-17 04.21.29.824862000 PM');
COMMIT;

INSERT INTO "PARKING_PARKINGPLACE" (ID, NAME, ADRESS, DESCRIPTION, PRICE_PER_HOUR)
VALUES (1, 'Place1', 'Adress1', 'Description1', 10);
COMMIT;
INSERT INTO "PARKING_PARKINGPLACE" (ID, NAME, ADRESS, DESCRIPTION, PRICE_PER_HOUR)
VALUES (2, 'Place2', 'Adress2', 'Description2', 20);
COMMIT;
INSERT INTO "PARKING_PARKINGPLACE" (ID, NAME, ADRESS, DESCRIPTION, PRICE_PER_HOUR)
VALUES (3, 'Place2', 'Adress2', 'Description2', 30);
COMMIT;

INSERT INTO "PARKING_CAR" (ID, CAR_PICTURE, MODEL)
VALUES (1, 'cars/no_car.jpg', 'Honda');
COMMIT;
INSERT INTO "PARKING_CAR" (ID, CAR_PICTURE, MODEL)
VALUES (2, 'cars/no_car.jpg', 'Mazda');
COMMIT;
INSERT INTO "PARKING_CAR" (ID, CAR_PICTURE, MODEL)
VALUES (3, 'cars/no_car.jpg', 'Toyota');
COMMIT;

INSERT INTO "PARKING_CAR_OWNER" (ID, CAR_ID, USER_ID)
VALUES (1, 1, 1);
COMMIT;
INSERT INTO "PARKING_CAR_OWNER" (ID, CAR_ID, USER_ID)
VALUES (2, 2, 2);
COMMIT;
INSERT INTO "PARKING_CAR_OWNER" (ID, CAR_ID, USER_ID)
VALUES (2, 3, 3);
COMMIT;
