/*======ROLES=======*/
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Admin', 'Керує системою');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Vacationer', 'Відпочиваючий, що обирає захід чи житло');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Landlord', 'Орендодавець, що надає житло');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Organizer', 'Організатор заходів');
/*======USERS=======*/
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, ID_CODE, SCAN_DOC_PATH) 
VALUES ('Admin', 'adm2in@site.ua', 'Адмін', 'rararara', '0663344222', 1232311231, NULL);
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, ID_CODE, SCAN_DOC_PATH) 
VALUES ('Vacationer', 'vac@site.ua', 'Петро', 'qwerty12', '0347261138', 123162331, NULL);
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, ID_CODE, SCAN_DOC_PATH) 
VALUES ('Organizer', 'org@site.ua', 'Іван', 'aiirrr3', '0974938123', 1231332599, NULL);
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, ID_CODE, SCAN_DOC_PATH) 
VALUES ('Landlord', 'apartment@site.ua', 'Джек', 'aopewr32', '0331323234', 1259012543, NULL);
/*======FACILITIES=======*/
INSERT INTO FACILITY (ORGANIZER_EMAIL_FK, FACILITY_ID, FACILITY_NAME, FACILITY_ADRESS, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('org@site.ua', 1, 'Rockfest', 'Київ, КПІ', TO_DATE('2018/06/07', 'yyyy/mm/dd'), TO_DATE('2018/06/10', 'yyyy/mm/dd'), 500, 300, 'Кращий фестиваль країни');
INSERT INTO FACILITY (ORGANIZER_EMAIL_FK, FACILITY_ID, FACILITY_NAME, FACILITY_ADRESS, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('org@site.ua', 2, 'Eatfest', 'Київ, КНУ', TO_DATE('2018/05/24', 'yyyy/mm/dd'), TO_DATE('2018/05/25', 'yyyy/mm/dd'), 150, 100, 'Фестиваль здорової їжі');
INSERT INTO FACILITY (ORGANIZER_EMAIL_FK, FACILITY_ID, FACILITY_NAME, FACILITY_ADRESS, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('org@site.ua', 3, 'Live', 'Київ, вднх', TO_DATE('2018/07/03', 'yyyy/mm/dd'), TO_DATE('2018/07/10', 'yyyy/mm/dd'), 600, 250, 'Жива музика');
INSERT INTO FACILITY (ORGANIZER_EMAIL_FK, FACILITY_ID, FACILITY_NAME, FACILITY_ADRESS, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('org@site.ua', 4, 'Designfest', 'Київ, Аркадія', TO_DATE('2018/06/05', 'yyyy/mm/dd'), TO_DATE('2018/09/05', 'yyyy/mm/dd'), 200, 310, 'Кращі дизайнери');
/*======APARTMENTS=======*/
INSERT INTO APARTMENT (LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('apartment@site.ua', 'Київ, Ковальський 2', 300, 'Одна кімната', 3, NULL);
INSERT INTO APARTMENT (LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('apartment@site.ua', 'Київ, Ковальський 3', 400, 'Одна кімната', 3, NULL);
INSERT INTO APARTMENT (LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('apartment@site.ua', 'Київ, Ковальський 4', 200, 'Одна кімната', 2, NULL);
INSERT INTO APARTMENT (LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('apartment@site.ua', 'Київ, Ковальський 5', 500, 'Дві кімната', 4, NULL);
/*======APARTMENTS` PHOTO=======*/
INSERT INTO APARTMENTPHOTO (LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PHOTO_PATH, PHOTO_DESC)
VALUES ('apartment@site.ua', 'Київ, Ковальський 2', 'static/1.jpg', '1');
INSERT INTO APARTMENTPHOTO (LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PHOTO_PATH, PHOTO_DESC)
VALUES ('apartment@site.ua', 'Київ, Ковальський 2', 'static/2.jpg', '2');
INSERT INTO APARTMENTPHOTO (LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PHOTO_PATH, PHOTO_DESC)
VALUES ('apartment@site.ua', 'Київ, Ковальський 2', 'static/3.jpg', '3');
INSERT INTO APARTMENTPHOTO (LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PHOTO_PATH, PHOTO_DESC)
VALUES ('apartment@site.ua', 'Київ, Ковальський 2', 'static/4.jpg', '4');
/*======BOOKED APARTMENTS=======*/
INSERT INTO BOOKAPARTMENTS (LANDLORD_EMAIL_FK, ADRESS_FK, BOOKER_EMAIL_FK, BOOKING_DATE, BOOKING_END, OPERATION_DATE)
VALUES ('apartment@site.ua', 'Київ, Ковальський 2', 'vac@site.ua', TO_DATE('2018/07/03', 'yyyy/mm/dd'), TO_DATE('2018/07/04', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO BOOKAPARTMENTS (LANDLORD_EMAIL_FK, ADRESS_FK, BOOKER_EMAIL_FK, BOOKING_DATE, BOOKING_END, OPERATION_DATE)
VALUES ('apartment@site.ua', 'Київ, Ковальський 3', 'vac@site.ua', TO_DATE('2018/07/07', 'yyyy/mm/dd'), TO_DATE('2018/07/08', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO BOOKAPARTMENTS (LANDLORD_EMAIL_FK, ADRESS_FK, BOOKER_EMAIL_FK, BOOKING_DATE, BOOKING_END, OPERATION_DATE)
VALUES ('apartment@site.ua', 'Київ, Ковальський 4', 'vac@site.ua', TO_DATE('2018/07/09', 'yyyy/mm/dd'), TO_DATE('2018/07/10', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO BOOKAPARTMENTS (LANDLORD_EMAIL_FK, ADRESS_FK, BOOKER_EMAIL_FK, BOOKING_DATE, BOOKING_END, OPERATION_DATE)
VALUES ('apartment@site.ua', 'Київ, Ковальський 5', 'vac@site.ua', TO_DATE('2018/07/10', 'yyyy/mm/dd'), TO_DATE('2018/07/11', 'yyyy/mm/dd'), SYSDATE);
/*======BOOKED FACILITIES=======*/
INSERT INTO BOOKFACILITIES (ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('org@site.ua', 1, 'vac@site.ua', SYSDATE);
INSERT INTO BOOKFACILITIES (ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('org@site.ua', 2, 'vac@site.ua', SYSDATE);
INSERT INTO BOOKFACILITIES (ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('org@site.ua', 3, 'vac@site.ua', SYSDATE);
INSERT INTO BOOKFACILITIES (ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('org@site.ua', 4, 'vac@site.ua', SYSDATE);

