/
/*======ROLES=======*/
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Admin', 'Керує системою');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Vacationer', 'Відпочиваючий, що обирає захід чи житло');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Landlord', 'Орендодавець, що надає житло');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Organizer', 'Організатор заходів');
/*======USERS=======*/
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, SCAN_DOC_PATH, IS_ACTIVE) 
VALUES ('Admin', 'adm2in@site.ua', 'Адмін', 'rararara', '0663344222', 'static/doc1.jpg', 0);
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, SCAN_DOC_PATH, IS_ACTIVE) 
VALUES ('Vacationer', 'vac@site.ua', 'Петро', 'qwerty12', '0347261138', 'static/doc2.jpg', 0);
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, SCAN_DOC_PATH, IS_ACTIVE) 
VALUES ('Organizer', 'org@site.ua', 'Іван', 'aiirrr3', '0974938123', 'static/doc3.jpg', 0);
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, SCAN_DOC_PATH, IS_ACTIVE) 
VALUES ('Landlord', 'apartment@site.ua', 'Джек', 'aopewr32', '0331323234', 'static/doc4.jpg', 0);
/*======FACILITIES=======*/
INSERT INTO FACILITY (ORGANIZER_EMAIL_FK, FACILITY_NAME, FACILITY_CITY, FACILITY_STREET, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('org@site.ua', 'Rockfest', 'Київ', 'КПІ', TO_DATE('2018/06/07', 'yyyy/mm/dd'), TO_DATE('2018/06/10', 'yyyy/mm/dd'), 500, 300, 'Кращий фестиваль країни');
INSERT INTO FACILITY (ORGANIZER_EMAIL_FK, FACILITY_NAME, FACILITY_CITY, FACILITY_STREET, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('org@site.ua', 'Eatfest', 'Київ', 'КНУ', TO_DATE('2018/05/24', 'yyyy/mm/dd'), TO_DATE('2018/05/25', 'yyyy/mm/dd'), 150, 100, 'Фестиваль здорової їжі');
INSERT INTO FACILITY (ORGANIZER_EMAIL_FK, FACILITY_NAME, FACILITY_CITY, FACILITY_STREET, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('org@site.ua', 'Live', 'Київ', 'Вднх', TO_DATE('2018/07/03', 'yyyy/mm/dd'), TO_DATE('2018/07/10', 'yyyy/mm/dd'), 600, 250, 'Жива музика');
INSERT INTO FACILITY (ORGANIZER_EMAIL_FK, FACILITY_NAME, FACILITY_CITY, FACILITY_STREET, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('org@site.ua', 'Designfest', 'Київ', 'Аркадія', TO_DATE('2018/06/05', 'yyyy/mm/dd'), TO_DATE('2018/09/05', 'yyyy/mm/dd'), 200, 310, 'Кращі дизайнери');
/*======APARTMENTS=======*/
INSERT INTO APARTMENT (LANDLORD_EMAIL_FK, CITY, STREET, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('apartment@site.ua', 'Київ', 'Ковальський 2', 300, 'Одна кімната', 3, NULL);
INSERT INTO APARTMENT (LANDLORD_EMAIL_FK, CITY, STREET, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('apartment@site.ua', 'Київ', 'Ковальський 3', 400, 'Одна кімната', 3, NULL);
INSERT INTO APARTMENT (LANDLORD_EMAIL_FK, CITY, STREET, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('apartment@site.ua', 'Київ', 'Ковальський 4', 200, 'Одна кімната', 2, NULL);
INSERT INTO APARTMENT (LANDLORD_EMAIL_FK, CITY, STREET, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('apartment@site.ua', 'Київ', 'Ковальський 5', 500, 'Дві кімната', 4, NULL);
/*======APARTMENTS` PHOTO=======*/
INSERT INTO APARTMENTPHOTO (ID, LANDLORD_EMAIL_FK, APARTMENT_PHOTO_PATH, PHOTO_DESC)
VALUES (1, 'apartment@site.ua', 'static/1.jpg', '1');
INSERT INTO APARTMENTPHOTO (ID, LANDLORD_EMAIL_FK, APARTMENT_PHOTO_PATH, PHOTO_DESC)
VALUES (2, 'apartment@site.ua', 'static/2.jpg', '1');
INSERT INTO APARTMENTPHOTO (ID, LANDLORD_EMAIL_FK, APARTMENT_PHOTO_PATH, PHOTO_DESC)
VALUES (3, 'apartment@site.ua', 'static/3.jpg', '1');
INSERT INTO APARTMENTPHOTO (ID, LANDLORD_EMAIL_FK, APARTMENT_PHOTO_PATH, PHOTO_DESC)
VALUES (4, 'apartment@site.ua', 'static/4.jpg', '1');
/*======BOOKED APARTMENTS=======*/
INSERT INTO BOOKAPARTMENTS (ID, LANDLORD_EMAIL_FK, BOOKER_EMAIL_FK, BOOKING_DATE, BOOKING_END, OPERATION_DATE)
VALUES (1, 'apartment@site.ua','vac@site.ua', TO_DATE('2018/07/03', 'yyyy/mm/dd'), TO_DATE('2018/07/04', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO BOOKAPARTMENTS (ID, LANDLORD_EMAIL_FK, BOOKER_EMAIL_FK, BOOKING_DATE, BOOKING_END, OPERATION_DATE)
VALUES (2, 'apartment@site.ua', 'vac@site.ua', TO_DATE('2018/07/07', 'yyyy/mm/dd'), TO_DATE('2018/07/08', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO BOOKAPARTMENTS (ID, LANDLORD_EMAIL_FK, BOOKER_EMAIL_FK, BOOKING_DATE, BOOKING_END, OPERATION_DATE)
VALUES (3, 'apartment@site.ua', 'vac@site.ua', TO_DATE('2018/07/09', 'yyyy/mm/dd'), TO_DATE('2018/07/10', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO BOOKAPARTMENTS (ID, LANDLORD_EMAIL_FK, BOOKER_EMAIL_FK, BOOKING_DATE, BOOKING_END, OPERATION_DATE)
VALUES (4, 'apartment@site.ua', 'vac@site.ua', TO_DATE('2018/07/10', 'yyyy/mm/dd'), TO_DATE('2018/07/11', 'yyyy/mm/dd'), SYSDATE);
/*======BOOKED FACILITIES=======*/
INSERT INTO BOOKFACILITIES (ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('org@site.ua', 1, 'vac@site.ua', SYSDATE);
INSERT INTO BOOKFACILITIES (ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('org@site.ua', 2, 'vac@site.ua', SYSDATE);
INSERT INTO BOOKFACILITIES (ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('org@site.ua', 3, 'vac@site.ua', SYSDATE);
INSERT INTO BOOKFACILITIES (ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('org@site.ua', 4, 'vac@site.ua', SYSDATE);