# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 00:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('add_to_bucket_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.Bucket')),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('picture', models.ImageField(blank=True, default='gift.jpg', upload_to='gifts/')),
                ('caregory', models.CharField(choices=[('Books', 'Books'), ('Flowers', 'Flowers'), ('Other', 'Other')], default='One', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='giftitemorder',
            name='gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.Gifts'),
        ),
        migrations.AlterUniqueTogether(
            name='bucket',
            unique_together=set([('user', 'name')]),
        ),
    ]
