INSERT INTO "USER" (USER_EMAIL, USER_FIRSTNAME, USER_LASTNAME, USER_PASS, USER_BIRTHDAY, USER_PHONE) VALUES ('qqq@q.qqq', 'Tom', 'Hanks', 'Hanks', TO_DATE('1965-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '+380661234567');
INSERT INTO "USER" (USER_EMAIL, USER_FIRSTNAME, USER_LASTNAME, USER_PASS, USER_BIRTHDAY, USER_PHONE) VALUES ('qwe@q.qwe', 'Sam', 'Loop', 'Hoop1234', TO_DATE('1960-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '+380961010101');
INSERT INTO "USER" (USER_EMAIL, USER_FIRSTNAME, USER_LASTNAME, USER_PASS, USER_BIRTHDAY, USER_PHONE) VALUES ('qqq@q.qa', 'Kate', 'Shri', 'LoveLove9', TO_DATE('2000-05-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '+380987654321');


INSERT INTO "IVANNA"."SPORT" (SPORT_NAME) VALUES ('Football');
INSERT INTO "IVANNA"."SPORT" (SPORT_NAME) VALUES ('Swimming');
INSERT INTO "IVANNA"."SPORT" (SPORT_NAME) VALUES ('Yoga');

INSERT INTO "IVANNA"."LOCATION_TYPE" (LOC_TYPE_NAME) VALUES ('Forest');
INSERT INTO "IVANNA"."LOCATION_TYPE" (LOC_TYPE_NAME) VALUES ('Pool');
INSERT INTO "IVANNA"."LOCATION_TYPE" (LOC_TYPE_NAME) VALUES ('Stadium');

INSERT INTO "INSTRUCTOR" (INSTRUCTOR_EMAIL, INSTRUCTOR_FIRSTNAME, INSTRUCTOR_LASTNAME, INSTRUCTOR_QUALIFICATION, INSTRUCTOR_PHONE, INSTRUCTOR_BIRTHDAY, INSTRUCTOR_SERTIFICATION1, INSTRUCTOR_MEDIC_EDUC, INSTRUCTOR_CAREER_START, INSTRUCTOR_EXTRA_INFO, INSTRUCTOR_PAYMENT) VALUES ('qqq@q.qq', 'Sher', 'Cock', 'Best trainer of the century', '+380669819657', TO_DATE('1966-02-21 21:22:58', 'YYYY-MM-DD HH24:MI:SS'), '123456fe', '1', TO_DATE('1990-11-29 21:23:29', 'YYYY-MM-DD HH24:MI:SS'), 'Nothing to say', '100');

INSERT INTO "INSTRUCTOR" (INSTRUCTOR_EMAIL, INSTRUCTOR_FIRSTNAME, INSTRUCTOR_LASTNAME, INSTRUCTOR_QUALIFICATION, INSTRUCTOR_PHONE, INSTRUCTOR_BIRTHDAY, INSTRUCTOR_SERTIFICATION1, INSTRUCTOR_MEDIC_EDUC, INSTRUCTOR_CAREER_START, INSTRUCTOR_EXTRA_INFO, INSTRUCTOR_PAYMENT) VALUES ('li@q.ua', 'Bob', 'Cock', 'Football trainer', '+380639876543', TO_DATE('1986-02-21 21:22:58', 'YYYY-MM-DD HH24:MI:SS'), '123456fe', '1', TO_DATE('2010-11-29 21:23:29', 'YYYY-MM-DD HH24:MI:SS'), 'Nothing to say', '50');

INSERT INTO "INSTRUCTOR" (INSTRUCTOR_EMAIL, INSTRUCTOR_FIRSTNAME, INSTRUCTOR_LASTNAME, INSTRUCTOR_QUALIFICATION, INSTRUCTOR_PHONE) VALUES ('QQQ@q.ua', 'Her', 'Cock', 'Best coach', '+380639819657')

INSERT INTO "LOCATION" (LOC_ID, LOC_TYPE_NAME, LOC_NAME, LOC_ADDRESS) VALUES ('1', 'Forest', 'ForestHall', 'Holoseevkii les, 123');
INSERT INTO "LOCATION" (LOC_ID, LOC_TYPE_NAME, LOC_NAME, LOC_ADDRESS, LOC_AREA, LOC_WATER, LOC_INSTUM, LOC_PAYMENT, LOC_POOL, LOC_RACE_TRACK, LOC_OPEN_TIME, LOC_CLOSE_TIME) VALUES ('2', 'Forest', 'ForHam', 'Holos Park, 5', '100', '+', '-', '0', '-', '+', '00:01', '23:59');
INSERT INTO "LOCATION" (LOC_ID, LOC_TYPE_NAME, LOC_NAME, LOC_ADDRESS, LOC_AREA, LOC_WATER, LOC_INSTUM, LOC_PAYMENT, LOC_POOL, LOC_RACE_TRACK, LOC_OPEN_TIME, LOC_CLOSE_TIME) VALUES ('3', 'Pool', 'KPIPool', 'Vozduhoflot. street, 34', '50', '-', '-', '300', '+', '+', '08:30', '18:00');

INSERT INTO "IVANNA"."INSTRUCTOR_SPORT" (SPORT_NAME, INSTRUCTOR_EMAIL) VALUES ('Football', 'li@q.ua');
INSERT INTO "INSTRUCTOR_SPORT" (SPORT_NAME, INSTRUCTOR_EMAIL) VALUES ('Swimming', 'QQQ@q.ua');
INSERT INTO "INSTRUCTOR_SPORT" (SPORT_NAME, INSTRUCTOR_EMAIL) VALUES ('Yoga', 'QQQ@q.ua');

INSERT INTO "TRAINING" (USER_EMAIL, LOC_ID, TRAINING_DATE, SPORT_NAME, INSTRUCTOR_EMAIL) VALUES ('qqq@q.qqq', '3', TO_DATE('2017-11-30 13:17:21', 'YYYY-MM-DD HH24:MI:SS'), 'Football', 'li@q.ua');
INSERT INTO "TRAINING" (USER_EMAIL, LOC_ID, TRAINING_DATE, SPORT_NAME, INSTRUCTOR_EMAIL) VALUES ('qqq@q.qqq', '3', TO_DATE('2017-12-10 13:17:21', 'YYYY-MM-DD HH24:MI:SS'), 'Football', 'li@q.ua');
INSERT INTO "TRAINING" (USER_EMAIL, LOC_ID, TRAINING_DATE, SPORT_NAME, INSTRUCTOR_EMAIL) VALUES ('qqq@q.qqq', '3', TO_DATE('2017-12-05 13:17:21', 'YYYY-MM-DD HH24:MI:SS'), 'Football', 'li@q.ua');





