CREATE TABLE "ARTICLES" 
   (	
   	"ARTICLE_ID" NUMBER, 
	"ARTICLE_TITLE" VARCHAR2(30 BYTE), 
	"ARTICLE_TEXT" VARCHAR2(1024 BYTE), 
	"ARTICLE_DATE" DATE, 
	PRIMARY KEY ("ARTICLE_ID")
   )

CREATE TABLE "CITIES" 
   (
   	"CITY_ID" NUMBER NOT NULL ENABLE, 
	"CITY_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	CONSTRAINT "PK_CITIES" PRIMARY KEY ("CITY_ID")
   )

CREATE TABLE "USERS" 
   (
   "USER_ID" NUMBER NOT NULL ENABLE, 
	"CITY_ID_FK" NUMBER NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BIRTHDAY" DATE NOT NULL ENABLE, 
	"REG_DATE" DATE NOT NULL ENABLE, 
	"ABOUT" VARCHAR2(150 BYTE), 
	"GENDER" NUMBER(*,0) NOT NULL ENABLE, 
	CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID"),
	CONSTRAINT "FK_USERS_USER_FROM_CITIES" FOREIGN KEY ("CITY_ID_FK")
	REFERENCES "CITIES" ("CITY_ID") ENABLE
   )

CREATE TABLE "DIALOGS" 
   (
   	"DIALOG_ID" NUMBER NOT NULL ENABLE, 
	"DIALOG_DATE" TIMESTAMP (6), 
	"SENDER_ID" NUMBER, 
	"RECIPIENT_ID" NUMBER, 
	CONSTRAINT "PK_DIALOGS" PRIMARY KEY ("DIALOG_ID"), 
	CONSTRAINT "SENDER_ID_FK" FOREIGN KEY ("SENDER_ID")
	REFERENCES "USERS" ("USER_ID") ENABLE, 
	CONSTRAINT "RECIPIENT_ID_FK" FOREIGN KEY ("RECIPIENT_ID")
	REFERENCES "USERS" ("USER_ID") ENABLE
   )

  CREATE TABLE "MESSAGES" 
   (	
   "MESSAGE_ID" NUMBER NOT NULL ENABLE, 
	"DIALOG_ID_FK" NUMBER NOT NULL ENABLE, 
	"USER_ID_FK" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"MESSAGE_DATE" TIMESTAMP (6), 
	CONSTRAINT "PK_MESSAGES" PRIMARY KEY ("MESSAGE_ID"),
	CONSTRAINT "FK_MESSAGES_DIALOG_HA_DIALOGS" FOREIGN KEY ("DIALOG_ID_FK")
	REFERENCES "DIALOGS" ("DIALOG_ID") ENABLE, 
	CONSTRAINT "FK_MESSAGES_USER_SEND_USERS" FOREIGN KEY ("USER_ID_FK")
	REFERENCES "USERS" ("USER_ID") ENABLE
   )

ALTER TABLE CITIES
	ADD CONSTRAINT CHECK_CITY_NAME
	CHECK (REGEXP_LIKE("CITY_NAME" , '[a-z]'));

ALTER TABLE "USERS"
  ADD CONSTRAINT EMAIL_UNIQUE UNIQUE ("EMAIL");

ALTER TABLE "USERS"
  ADD CONSTRAINT EMAIL_UNIQUE UNIQUE ("EMAIL");

ALTER TABLE "USERS"
  ADD CONSTRAINT CHECK_PASS
  CHECK ( REGEXP_LIKE ("PASSWORD", '[A-Za-z 0-9.,!#$%^&*_]{6,20}'));

ALTER TABLE "USERS"
  ADD CONSTRAINT CHECK_PASS_LEN
  CHECK(length("PASSWORD")>6 and length("PASSWORD")<20);

ALTER TABLE "USERS"
  ADD CONSTRAINT "NAME_CHECK" 
  CHECK (REGEXP_LIKE("NAME", '^[A-Z][a-zA-Z]{2,32}$'));

ALTER TABLE "USERS"
  ADD CONSTRAINT CHECK_NAME_LEN
  CHECK(length("NAME")>2 and length("NAME")<20);
  
ALTER TABLE "USERS"
  ADD CONSTRAINT CHECK_ABOUT_LEN
  CHECK(length("ABOUT")>2 and length("ABOUT")<150); 
  
ALTER TABLE USERS
  ADD CONSTRAINT CHECK_AGE
    CHECK("BIRTHDAY" > DATE '2001-01-01');

ALTER TABLE MESSAGES
  ADD CONSTRAINT MESSAGE_LEN
  CHECK(length("TEXT")>1 and length("TEXT")<200);


/*
create or replace TRIGGER ADD_USER_T
INSTEAD OF INSERT ON USER_TABLE_V
DECLARE
BEGIN
    INSERT INTO USERS (USER_ID, NAME, EMAIL, CITY_ID_FK, PASSWORD, BIRTHDAY, GENDER, REG_DATE) 
    VALUES (:user_id, :user_name, :user_email, :city_id, :user_password, 
    	TO_DATE(:user_birthday, 'DD.MM.YYYY'), :user_gender, CURRENT_TIMESTAMP);
END ADD_USER_T;
/

create or replace TRIGGER DELETE_SOME_USER
INSTEAD OF DELETE ON USER_TABLE_V
DECLARE
BEGIN
   UPDATE "USER" 
   SET "DELETED" = 'Y'
   WHERE "ROLE" = :OLD."ROLE" and "EMAIL" = :OLD."EMAIL"; 
END DELETE_SOME_USER;
/

CREATE VIEW USER_TABLE
AS
SELECT *
FROM "USERS"
WHERE USER_ID = :$_COOKIE['uid'];

create or replace TRIGGER ADD_USER_T
INSTEAD OF INSERT ON USER_TABLE
DECLARE
BEGIN
    INSERT INTO USERS (USER_ID, NAME, EMAIL, CITY_ID_FK, PASSWORD, BIRTHDAY, GENDER, REG_DATE) 
    VALUES (:user_id, :user_name, :user_email, :city_id, :user_password, 
    	TO_DATE(:user_birthday, 'DD.MM.YYYY'), :user_gender, CURRENT_TIMESTAMP);
END ADD_USER_T;
/*/
