--For User
INSERT INTO "OKSANA"."User" (USER_ID, USER_FIRSTNAME, USER_SECONDNAME, USER_EMAIL, USER_PASS, USER_TYPE) VALUES ('1', 'Oksana', 'Mykolenko', 'mykolenko@gmail.com', 'qwertyqwerty', '0');
INSERT INTO "OKSANA"."User" (USER_ID, USER_FIRSTNAME, USER_SECONDNAME, USER_EMAIL, USER_PASS, USER_TYPE) VALUES ('2', 'Kate', 'Midelton', 'midelton@gmail.com', 'qwertyqwerty2', '1');
INSERT INTO "OKSANA"."User" (USER_ID, USER_FIRSTNAME, USER_SECONDNAME, USER_EMAIL, USER_PASS, USER_TYPE) VALUES ('3', 'Vova', 'Kozyk', 'kozyk@gmail.com', 'qwertyqwerty21', '2');
--For Flat
INSERT INTO "OKSANA"."FLAT" (FLAT_ADRESS, FLAT_PRICE, FLAT_TYPE, FLAT_DESCRIPTION) VALUES ('Kyiv, Stritenska Str, flat 96', '100', 'Apartments', 'Great flat');
INSERT INTO "OKSANA"."FLAT" (FLAT_ADRESS, FLAT_PRICE, FLAT_TYPE, FLAT_DESCRIPTION) VALUES ('Kyiv, Stritenska Str, flat 967', '100', 'Flat', 'Beautiful flat in the city center, if you like museums, you will probably like it');
INSERT INTO "OKSANA"."FLAT" (FLAT_ADRESS, FLAT_PRICE, FLAT_TYPE, FLAT_DESCRIPTION) VALUES ('Kyiv, Gogolivska Str, flat 6', '100', 'Apartments', 'Great flat in center');
--For Booking
INSERT INTO "OKSANA"."BOOKING" (BOOKING_ID, BOOKING_STATUS, BOOKING_STARTDATE, BOOKING_FINISHDATE, HOST_ID_FK, GUEST_ID_FK, FLAT_ADRESS_FK) VALUES ('1', '1', TO_DATE('2017-11-25 16:29:38', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2017-11-30 16:29:42', 'YYYY-MM-DD HH24:MI:SS'), '1', '2', 'Kyiv, Gogolivska Str, flat 6');
INSERT INTO "OKSANA"."BOOKING" (BOOKING_ID, BOOKING_STATUS, BOOKING_STARTDATE, BOOKING_FINISHDATE, HOST_ID_FK, GUEST_ID_FK, FLAT_ADRESS_FK) VALUES ('2', '1', TO_DATE('2018-11-25 16:29:38', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-11-30 16:29:42', 'YYYY-MM-DD HH24:MI:SS'), '1', '2', 'Kyiv, Gogolivska Str, flat 6');
INSERT INTO "OKSANA"."BOOKING" (BOOKING_ID, BOOKING_STATUS, BOOKING_STARTDATE, BOOKING_FINISHDATE, HOST_ID_FK, GUEST_ID_FK, FLAT_ADRESS_FK) VALUES ('3', '1', TO_DATE('2019-11-25 16:29:38', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2019-11-30 16:29:42', 'YYYY-MM-DD HH24:MI:SS'), '1', '2', 'Kyiv, Gogolivska Str, flat 6');
